version: '3.7'

services:
  web:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      DATABASE_URL: mongodb://root:password@mongo:27018/parking?authSource=admin

  mongo:
    image: 'mongo:latest'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - '27018:27018'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
