name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: '8.0'
          mongodb-db: parking-test

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Run tests
        env:
          TEST_DATABASE_URL: mongodb://localhost:27017/parking-test
        run: |
          npm install
          npm run test
          npm run test:e2e

      - name: Generate tag
        run: echo ::set-output name=tag::$(echo $GITHUB_SHA | head -c 7)
        id: tag

      - name: Login into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: parkournick3/mlabs-teste-tecnico:${{ steps.tag.outputs.tag }},parkournick3/mlabs-teste-tecnico:latest
